use cql_bindgen::cass_retry_policy_default_new;
use cql_bindgen::cass_retry_policy_downgrading_consistency_new;
use cql_bindgen::cass_retry_policy_fallthrough_new;
use cql_bindgen::cass_retry_policy_free;
use cql_bindgen::cass_retry_policy_logging_new;
